# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changemenow
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_secret_access_key_id: <%= ENV['AWS_SECRET_ACCESS_KEY_ID'] %>
  domain_name: example.com
  email_provider_username: <%= ENV['SENDGRID_USERNAME'] %>
  email_provider_apikey: <%= ENV['SENDGRID_PASSWORD'] %>
  github_key: <%= ENV['GITHUB_KEY'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>
  mailchimp_username: <%= ENV['MAILCHIMP_USERNAME'] %>
  mailhimp_password: <%= ENV['MAILCHIMP_PASSWORD'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
  omniauth_app_id: <%= ENV['OMNIAUTH_APP_ID'] %>
  omniauth_app_secret: <%= ENV['OMNIAUTH_APP_SECRET'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  secret_key: <%= ENV['SECRET_KEY'] %>
  secret_token: <%= ENV['SECRET_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  sendgrid_smtp_username: <%= ENV['SMTP_USER_NAME'] %>
  sendgrid_smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  # stripe_api_key: <%= ENV['STRIPE_API_KEY'] %>
  # stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>

test:
  domain_name: example.com
  secret_key_base: 6d1ef5c210624318304552d43412ab8440259b2e44429c5af841090fb8256816ad5224a778848989fe262ab3a0c1460aee7b7f0f79255a0d6f27b99e6ae8abd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV['ADMIN_NAME'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  # TODO: 20160409 : see note in development
  email_provider_username: <%= ENV['SENDGRID_USERNAME'] %>
  email_provider_apikey: <%= ENV['SENDGRID_PASSWORD'] %>
  domain_name: <%= ENV['DOMAIN_NAME'] %>
  github_key: <%= ENV['GITHUB_KEY'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>
  # stripe_api_key: <%= ENV['STRIPE_API_KEY'] %>
  # stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

